## HBase 配置
hbase:
  config:
    hbase:
      zookeeper:
        quorum: 172.17.0.2
        port: 2181
#        znode: /hadoop/data_ha
      master: 172.17.0.2:16000
      client:
        keyvalue:
          maxsize: 1572864000

server:
  port: 8001
